"use client"

import { ArrowUp, Paperclip, Plus, Square, Wrench } from "lucide-react"
import { useRef } from "react"
import type { Tool } from "@/lib/types"
import { ModelPicker } from "./ModelPicker"
import type { Model } from "@/lib/types"

export function ChatComposer({ value, onChange, onSend, loading, models, selectedModel, onModelChange, tools, selectedTools, onToolsChange, canSend }: { value: string; onChange: (value: string) => void; onSend: () => void; loading: boolean; models: Model[]; selectedModel?: string; onModelChange: (id: string) => void; tools: Tool[]; selectedTools: string[]; onToolsChange: (ids: string[]) => void; canSend: boolean }) {
  const inputRef = useRef<HTMLTextAreaElement>(null)
  const toggleTool = (id: string) => onToolsChange(selectedTools.includes(id) ? selectedTools.filter((toolId) => toolId !== id) : [...selectedTools, id])
  return <div className="w-full max-w-[860px] px-4 pb-4 sm:px-6"><div className="border border-[var(--ai-border)] bg-[var(--ai-panel)] transition-colors focus-within:border-[var(--ai-accent)]/50 focus-within:shadow-[0_0_24px_var(--ai-accent-glow)]"><textarea ref={inputRef} value={value} onChange={(event) => onChange(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSend() } }} disabled={loading} rows={3} placeholder="Message your AI..." className="block max-h-40 min-h-[76px] w-full resize-none bg-transparent px-4 py-3 text-sm leading-6 text-[var(--ai-text)] outline-none placeholder:text-[var(--ai-muted)] disabled:opacity-50" /><div className="flex items-center justify-between border-t border-[var(--ai-border)] px-3 py-2"><div className="flex items-center gap-1"><button aria-label="Attach file" disabled title="Attachments are not connected" className="p-1.5 text-[var(--ai-muted)] opacity-50"><Paperclip className="h-4 w-4" /></button><div className="group relative"><button aria-label="Select tools" className={`flex items-center gap-1.5 p-1.5 font-mono text-[10px] uppercase tracking-widest ${selectedTools.length ? "text-[var(--ai-accent)]" : "text-[var(--ai-muted)]"}`}><Plus className="h-3.5 w-3.5" /><Wrench className="h-3.5 w-3.5" />Tools</button>{tools.length > 0 && <div className="absolute bottom-8 left-0 z-20 hidden w-52 border border-[var(--ai-border)] bg-[#0c0d0b] p-2 shadow-2xl group-focus-within:block group-hover:block">{tools.map((tool) => <label className="flex cursor-pointer items-center gap-2 px-2 py-2 text-xs text-[var(--ai-muted)] hover:bg-white/5" key={tool.id}><input type="checkbox" checked={selectedTools.includes(tool.id)} onChange={() => toggleTool(tool.id)} className="accent-[var(--ai-accent)]" />{tool.name}</label>)}</div>}</div></div><div className="flex items-center gap-3"><div className="hidden sm:block"><ModelPicker models={models} value={selectedModel} onChange={onModelChange} /></div><button aria-label={loading ? "Stop generation" : "Send message"} onClick={onSend} disabled={!canSend && !loading} className="grid h-7 w-7 place-items-center bg-[var(--ai-accent)] text-black transition-opacity hover:opacity-80 disabled:cursor-not-allowed disabled:opacity-30">{loading ? <Square className="h-3 w-3 fill-current" /> : <ArrowUp className="h-4 w-4" />}</button></div></div></div></div>
}